=== c-jar/2022-Compilation_2-TD/TD3/ListePieces.dtd
<!ELEMENT ListePieces (Piece+)>
<!ELEMENT Piece (Description,Prix)>
<!ELEMENT Prix (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ATTLIST Piece
	reference ID #REQUIRED
	modele (2CV|Mini|Coccinelle) "2CV"
	disponibilite (unique|
	commandable_chez_constructeur) "unique"
	etat (neuf|stock_invendu|occasion) "neuf">

=== c-jar/2022-Compilation_2-TD/TD3/stock.xml
<?xml version="1.0" ?>
<!DOCTYPE ListePieces SYSTEM "ListePieces.dtd">
<ListePieces>
	<Piece reference="P834" modele="2CV" disponibilite="unique" etat="neuf">
		<Description>Pot d'échappement</Description>
		<Prix>150€</Prix>
	</Piece>
	<Piece reference="T563" modele="Mini"
		disponibilite="commandable_chez_constructeur" etat="neuf">
		<Description>sigle</Description>
		<Prix>50€</Prix>
	</Piece>
	<Piece reference="M546" modele="2CV" disponibilite="unique" etat="occasion">
		<Description>volant</Description>
		<Prix>100€</Prix>
	</Piece>
</ListePieces>
