=== c-jar/2022-Compilation_2-TD/TD3/work/ListePieces_avec_lot.dtd
<!ELEMENT ListePieces (Piece|Lot)+>
	<!ELEMENT Piece (Description,Prix) >
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT Prix (#PCDATA)>
	<!ATTLIST Piece 
		reference ID #REQUIRED
		modele (Coccinelle|2CV|Mini) #REQUIRED 
		dispo (unique|commandable_chez_constructeur) "unique"
		etat (neuf|stock_invendu|occasion) #REQUIRED 
		test CDATA #IMPLIED>
<!ELEMENT Lot (Nom,Prix)>
<!ELEMENT Nom (#PCDATA)>
<!ATTLIST Lot 
	references IDREFS #REQUIRED>

=== c-jar/2022-Compilation_2-TD/TD3/work/stock_lot.xml
<?xml version="1.0" ?>
<!DOCTYPE ListePieces SYSTEM "ListePieces_avec_lot.dtd">
<ListePieces>
	<Piece reference="P834" modele="2CV" dispo="unique" etat="neuf">
		<Description>Pot d'échappement</Description>
		<Prix>150€</Prix>
	</Piece>
	<Piece reference="T563" modele="Mini" dispo="unique" etat="neuf">
		<Description>sigle</Description>
		<Prix>50€</Prix>
	</Piece>
	<Piece reference="M546" modele="2CV" dispo="unique" etat="occasion">
		<Description>volant</Description>
		<Prix>100€</Prix>
	</Piece>
	<Lot references="P834 M543">
		<Nom> Lot pour 2CV</Nom>
		<Prix> 200 €</Prix>
	</Lot>
</ListePieces>
